- name: Deploy Docker Image
  hosts: all
  tasks:
  
    - name: Deploy Application
      docker_container:
        name: Java Assessment
        image: takowtakow/test-repo/devops-assessment:latest
        state: started
        ports:
          - "8080:8080"
