- name: Deploy Docker Image
  hosts: all
  tasks:
  
    - name: Deploy Application
      docker_container:
        name: Devops Assessment
        image: takowtakow/test-repo:deveops-assessment
        state: started
        ports:
          - "8080:8080"
