name: Devops Assessment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    #container:
    #  image: maven:3.6.3-jdk-11

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6

    - name: Build
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Run application
      run: mvn exec:java
    
    - name: Install Docker
      uses: docker-practice/actions-setup-docker@master
      # #if: failure()
      # run: |
      #   # Update the package index
      #   sudo apt-get update
        
      #   # Install packages to allow apt to use a repository over HTTPS
      #   sudo apt-get install -y \
      #       apt-transport-https \
      #       ca-certificates \
      #       curl \
      #       gnupg \
      #       lsb-release
        
      #   # Add Docker's official GPG key
      #   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        
      #   # Set up the stable repository
      #   echo \
      #     "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      #     $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
      #   # Install Docker Engine
      #   sudo apt-get update
      #   sudo apt-get install -y docker-ce docker-ce-cli containerd.io
        
    - name: Check Docker version
      # needs: Install Docker
      run: docker version

    - name: Build Docker image
      # needs: Install Docker
      run: docker build -t devops-assessment:latest .

    - name: Save Docker image
      run: docker save devops-assessment:latest -o devops-assessmentv1.tar

    - name: Upload Docker image to GitHub artifacts
      uses: actions/upload-artifact@v2
      with:
        name: takow-assessment
        path: devops-assessmentv1.tar