name: Devops Assessment

on:
   push:
    branches: [ main ]

jobs:
   build:

     runs-on: self-hosted
    # Enable GitHub runner reuse
     continue-on-error: true

     steps:

     - name: Set REPO_URL
       run: |
        REPO_URL=https://github.com/${{ github.repository }}.git
        echo "REPO_URL=$REPO_URL" >> $GITHUB_OUTPUT

     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Set up JDK
       uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
    
     - name: Install Maven
       uses: stCarolas/setup-maven@v4.5
       with:
        maven-version: 3.8.6

     - name: Build
       run: mvn compile

     - name: Test
       run: mvn test

     - name: Run application
       run: mvn exec:java
        
        
    #     # Add current user to the docker group
    #     #sudo usermod -aG docker $USER
    #     sudo /etc/init.d/docker start
    #     # Verify Docker installation
    #     docker version
     
     - name: Start Docker Daemon
       run: |
        # Start the Docker daemon
        sudo /etc/init.d/docker start
     
    #  - name: hello world
    #    run: |
    #      sudo docker run hello-world

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3
      
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
      
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

     -  name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: takow/devops_assessment:latest

    #  - name: Build
    #    uses: cloudposse/github-action-docker-build-push@main
    #    with:
    #     registry: registry.hub.docker.com
    #     organization: "${{ github.event.repository.owner.login }}"
    #     repository: "${{ github.event.repository.name }}"
    #     login: "${{ secrets.DOCKER_USERNAME }}"
    #     password: "${{ secrets.DOCKER_PASSWORD }}"
        
    #    outputs:
    #      image: ${{ steps.build.outputs.image }}
    #      tag: ${{ steps.build.outputs.tag }}

     - name: Set up python for Ansible
       uses: actions/setup-python@v4
       with:
        python-version: '3.x'
        
     - name: Install Ansible Docker Module
       run: |
        python -m pip install --upgrade pip
        pip install ansible docker

     - name: Deploy application with Ansible
       run:  |
        ansible-playbook -i iventory ./ansible/deploy.yaml
       env: 
        DOCKER_IMAGE_TAG: devops_assessment:latest
