name: Devops Assessment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
    #container:
    #  image: maven:3.6.3-jdk-11

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6

    - name: Build
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Run application
      run: mvn exec:java

    - name: Build Docker image
      run: docker build -t devops-assessment:latest .

    - name: Save Docker image to
      run: docker save devops-assessment:latest -o devops-assessmentv1.tar

    - name: Upload Docker image to GitHub artifacts
      uses: actions/upload-artifact@v2
      with:
        name: takow-assessment
        path: devops-assessmentv1.tar